In [1]:
import pandas as pd 
data = pd.read_csv("filtered_omni_math.csv")
data.head()

,domain,difficulty,problem,solution,answer,source
0,['Mathematics -> Geometry -> Plane Geometry ->...,7.0,"In an acute scalene triangle $ABC$, points $D,...","\nIn an acute scalene triangle \(ABC\), points...",1,usa_team_selection_test
1,['Mathematics -> Geometry -> Plane Geometry ->...,7.0,"For a pair $ A \equal{} (x_1, y_1)$ and $ B \e...","\nGiven a set of 100 points in the plane, we w...",3750,usa_team_selection_test
2,['Mathematics -> Geometry -> Plane Geometry ->...,7.0,Draw a $2004 \times 2004$ array of points. Wha...,\nTo determine the largest integer \( n \) for...,561,usa_team_selection_test
3,['Mathematics -> Discrete Mathematics -> Graph...,7.0,Given $30$ students such that each student has...,\nGiven 30 students such that each student has...,6,china_national_olympiad
4,['Mathematics -> Discrete Mathematics -> Combi...,7.0,"Let $f:X\rightarrow X$, where $X=\{1,2,\ldots ...","\nLet \( f: X \rightarrow X \), where \( X = \...",69,china_national_olympiad

In [2]:
data['difficulty'].value_counts()

difficulty
5.000    421
4.000    286
4.500    182
1.500    132
2.000    124
2.500    123
5.250    108
3.500    103
1.000     80
6.000     60
5.500     50
7.000     47
8.000     31
9.000     25
3.000     13
6.500     11
4.750      6
7.500      5
2.250      3
9.500      3
6.250      2
4.375      1
3.750      1
8.500      1
Name: count, dtype: int64

In [3]:
# Filter the dataset for difficulty 9 or higher
filtered_data = data[data['difficulty'] >= 9]
filtered_data.head()

,domain,difficulty,problem,solution,answer,source
12,['Mathematics -> Discrete Mathematics -> Graph...,9.0,Let $G$ be a simple graph with 100 vertices su...,\nLet \( G \) be a simple graph with 100 verti...,3822,china_team_selection_test
20,['Mathematics -> Algebra -> Intermediate Algeb...,9.0,"Find the smallest positive number $\lambda $ ,...",\nWe aim to find the smallest positive number ...,1,china_team_selection_test
21,['Mathematics -> Algebra -> Algebra -> Equatio...,9.0,"Define the sequences $(a_n),(b_n)$ by\n\begin{...",\n\nDefine the sequences \( (a_n) \) and \( (b...,199,china_national_olympiad
34,['Mathematics -> Algebra -> Linear Algebra -> ...,9.0,FIx positive integer $n$. Prove: For any posit...,\nFix a positive integer \( n \). We aim to pr...,0,china_team_selection_test
1603,['Mathematics -> Calculus -> Differential Calc...,9.0,For a nonnegative integer $n$ and a strictly i...,The minimum value of $T$ is 29. Write $t_{n+1}...,29,putnam

In [4]:
filtered_data.to_csv("high_difficulty_omni_math.csv", index=False)